# Generated by Django 4.1.7 on 2023-04-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATCdash', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
